/* Header file for function FileSystem
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void filesystem_startup(void);

/* Provided interfaces */
void filesystem_PI_file_handling_create_file( const asn1SccAPP_MARKER_REPOSITORY_PATH *, const asn1SccAPP_MARKER_MAXIMUM_SIZE *, const asn1SccAPP_MARKER_ADDITIONAL_FILE_ATTRIBUTE *, asn1SccAPP_MARKER_BOOLEAN * );


void filesystem_PI_file_handling_delete_file( const asn1SccAPP_MARKER_FILE_PATH *, asn1SccAPP_MARKER_BOOLEAN * );


void filesystem_PI_read_object_memory( const asn1SccAPP_MARKER_MEMORY_BASE *, const asn1SccAPP_MARKER_MEMORY_OFFSET *, const asn1SccAPP_MARKER_MEMORY_OFFSET *, asn1SccAPP_MARKER_MEMORY_DATA *, asn1SccAPP_MARKER_BOOLEAN * );


void filesystem_PI_report_content_of_repository_request( const asn1SccAPP_MARKER_REPOSITORY_PATH * );


void filesystem_PI_write_object_memory( const asn1SccAPP_MARKER_MEMORY_BASE *, const asn1SccAPP_MARKER_MEMORY_OFFSET *, const asn1SccAPP_MARKER_MEMORY_DATA *, asn1SccAPP_MARKER_BOOLEAN * );

/* Required interfaces */
extern void filesystem_RI_memory_erase( const asn1SccMEMORY_BLOCK_INDEX *, asn1SccT_Int32 * );


extern void filesystem_RI_memory_program( const asn1SccMEMORY_BLOCK_INDEX *, const asn1SccMEMORY_OFFSET *, const asn1SccMEMORY_DATA *, const asn1SccMEMORY_SIZE *, asn1SccT_Int32 * );


extern void filesystem_RI_memory_read( const asn1SccMEMORY_BLOCK_INDEX *, const asn1SccMEMORY_OFFSET *, asn1SccMEMORY_DATA *, const asn1SccMEMORY_SIZE *, asn1SccT_Int32 * );


extern void filesystem_RI_memory_sync( asn1SccT_Int32 * );


extern void filesystem_RI_report_content_of_repository_request_respond( const asn1SccAPP_MARKER_REPOSITORY_PATH *, asn1SccALPHA_REPOSITORY_OBJECTS * );


#ifdef __cplusplus
}
#endif
