/* Body file for function FileSystem
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "filesystem.h"
#include "lfs.h"

int block_device_read(const struct lfs_config *c, lfs_block_t block,
			lfs_off_t off, void *buffer, lfs_size_t size);

int block_device_prog(const struct lfs_config *c, lfs_block_t block,
	    lfs_off_t off, const void *buffer, lfs_size_t size);

int block_device_erase(const struct lfs_config *c, lfs_block_t block);

int block_device_sync(const struct lfs_config *c);

lfs_t lfs;
lfs_file_t file;

const struct lfs_config cfg = {
    .read  = block_device_read,
    .prog  = block_device_prog,
    .erase = block_device_erase,
    .sync  = block_device_sync,

    .read_size = 16,
    .prog_size = 16,
    .block_size = 4096,
    .block_count = 128,
    .block_cycles = 500,
    .cache_size = 16,
    .lookahead_size = 16,
};


void filesystem_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[FileSystem] Startup");
}

void filesystem_PI_file_handling_create_file
      (const asn1SccAPP_MARKER_REPOSITORY_PATH *IN_object_path,
       const asn1SccAPP_MARKER_MAXIMUM_SIZE *IN_maximum_size,
       const asn1SccAPP_MARKER_ADDITIONAL_FILE_ATTRIBUTE *IN_attributes,
       asn1SccAPP_MARKER_BOOLEAN *OUT_result)

{
   // Write your code here
}


void filesystem_PI_file_handling_delete_file
      (const asn1SccAPP_MARKER_FILE_PATH *IN_object_path,
       asn1SccAPP_MARKER_BOOLEAN *OUT_result)

{
   // Write your code here
}


void filesystem_PI_read_object_memory
      (const asn1SccAPP_MARKER_MEMORY_BASE *IN_memory_base,
       const asn1SccAPP_MARKER_MEMORY_OFFSET *IN_offset,
       const asn1SccAPP_MARKER_MEMORY_OFFSET *IN_length,
       asn1SccAPP_MARKER_MEMORY_DATA *OUT_content,
       asn1SccAPP_MARKER_BOOLEAN *OUT_result)

{
   // Write your code here
}


void filesystem_PI_report_content_of_repository_request
      (const asn1SccAPP_MARKER_REPOSITORY_PATH *IN_repository_path)

{
   // Write your code here
}


void filesystem_PI_write_object_memory
      (const asn1SccAPP_MARKER_MEMORY_BASE *IN_memory_base,
       const asn1SccAPP_MARKER_MEMORY_OFFSET *IN_offset,
       const asn1SccAPP_MARKER_MEMORY_DATA *IN_content,
       asn1SccAPP_MARKER_BOOLEAN *OUT_result)

{
   // Write your code here
}

int block_device_read(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, void *buffer, lfs_size_t size)
{
	const asn1SccMEMORY_BLOCK_INDEX block_index = block;
	const asn1SccMEMORY_OFFSET block_offset = off;
	asn1SccMEMORY_DATA data;
	const asn1SccMEMORY_SIZE data_size = size;
	asn1SccT_Int32 return_code;

	filesystem_RI_memory_read(&block_index, &block_offset, &data, &data_size, &return_code);

	return return_code;
}

int block_device_prog(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, const void *buffer, lfs_size_t size)
{

}

int block_device_erase(const struct lfs_config *c, lfs_block_t block)
{

}

int block_device_sync(const struct lfs_config *c)
{

}


