/* Body file for function FileSystem
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#define LFS_NO_MALLOC
#define LFS_YES_TRACE

#include "filesystem.h"
#include "lfs.h"
#include "stdint.h"
#include "string.h"

#define MAXIMUM_OBJECT_THAT_CAN_BE_REPORTED 64

int block_device_read(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, void *buffer, lfs_size_t size);

int block_device_prog(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, const void *buffer, lfs_size_t size);

int block_device_erase(const struct lfs_config *c, lfs_block_t block);

int block_device_sync(const struct lfs_config *c);

lfs_t lfs;

struct lfs_config cfg = {
    .read = block_device_read,
    .prog = block_device_prog,
    .erase = block_device_erase,
    .sync = block_device_sync,

    .read_size = 16,
    .prog_size = 16,
    .block_size = 4096,
    .block_count = 128,
    .block_cycles = 500,
    .cache_size = 16,
    .lookahead_size = 16,
};

void filesystem_startup(void)
{
	if (0 < lfs_format(&lfs, &cfg)) {
		printf("[FileSystem] format error\n");
		exit(EXIT_FAILURE);
	}
	if (0 < lfs_mount(&lfs, &cfg)) {
		printf("[FileSystem] mount error\n");
		exit(EXIT_FAILURE);
	}
}

void filesystem_PI_file_handling_create_file(
    const asn1SccGAMMA_REPOSITORY_PATH *IN_object_path,
    const asn1SccGAMMA_MAXIMUM_SIZE *IN_maximum_size,
    const asn1SccGAMMA_ADDITIONAL_FILE_ATTRIBUTE *IN_attributes,
    asn1SccGAMMA_BOOLEAN *OUT_result)

{
	lfs_file_t file;
	uint8_t buffer[cfg.cache_size];
	memset(buffer, 0, cfg.cache_size);

	struct lfs_attr file_attr = {.type = 0,
				     .buffer = IN_attributes->field_data.arr,
				     .size = IN_attributes->field_data.nCount};

	struct lfs_file_config file_config = {
	    .buffer = buffer, .attrs = &file_attr, .attr_count = 1};

	int return_code =
	    lfs_file_opencfg(&lfs, &file, IN_object_path->field_data,
			     LFS_O_RDWR | LFS_O_CREAT, &file_config);
	if (return_code < 0) {
		*OUT_result = false;
		return;
	}

	return_code = lfs_file_close(&lfs, &file);
	*OUT_result = return_code == 0;
}

void filesystem_PI_file_handling_delete_file(
    const asn1SccGAMMA_FILE_PATH *IN_object_path,
    asn1SccGAMMA_BOOLEAN *OUT_result)

{
	int return_code =
	    lfs_remove(&lfs, IN_object_path->file_name.field_data);
	*OUT_result = return_code == 0;
}

void filesystem_PI_read_object_memory(
    const asn1SccGAMMA_MEMORY_BASE *IN_memory_base,
    const asn1SccGAMMA_MEMORY_OFFSET *IN_offset,
    const asn1SccGAMMA_MEMORY_OFFSET *IN_length,
    asn1SccGAMMA_MEMORY_DATA *OUT_content, asn1SccGAMMA_BOOLEAN *OUT_result)

{
	if (IN_memory_base->kind != GAMMA_MEMORY_BASE_fs_memory_PRESENT) {
		*OUT_result = false;
		return;
	}

	lfs_file_t file;
	int offset = *IN_offset;
	int length = *IN_length;

	uint8_t buffer[cfg.cache_size];
	memset(buffer, 0, cfg.cache_size);

	struct lfs_attr file_attrs[8];

	struct lfs_file_config file_config = {
	    .buffer = buffer, .attrs = file_attrs, .attr_count = 0};

	int return_code = lfs_file_opencfg(
	    &lfs, &file, IN_memory_base->u.fs_memory.field_data,
	    LFS_O_RDWR | LFS_O_CREAT, &file_config);
	if (return_code < 0) {
		*OUT_result = false;
		return;
	}

	if (offset != lfs_file_seek(&lfs, &file, offset, LFS_SEEK_SET)) {
		*OUT_result = false;
		return;
	}

	if (length !=
	    lfs_file_read(&lfs, &file, OUT_content->field_data.arr, length)) {
		*OUT_result = false;
		return;
	}
	OUT_content->field_data.nCount = length;

	return_code = lfs_file_close(&lfs, &file);
	if (return_code < 0) {
		*OUT_result = false;
		return;
	}

	*OUT_result = true;
}

void filesystem_PI_report_content_of_repository_request(
    const asn1SccGAMMA_REPOSITORY_PATH *IN_repository_path)

{
	lfs_dir_t dir;
	struct lfs_info info;
	asn1SccALPHA_REPOSITORY_OBJECTS repo_objects;
	repo_objects.field_data.nCount = 0;

	int return_code =
	    lfs_dir_open(&lfs, &dir, IN_repository_path->field_data);
	if (return_code < 0) {
		printf("[FileSystem] could not open a dir\n");
		return;
	}

	while (lfs_dir_read(&lfs, &dir, &info) > 0 &&
	       repo_objects.field_data.nCount <
		   MAXIMUM_OBJECT_THAT_CAN_BE_REPORTED) {
		if (info.type == LFS_TYPE_DIR) {
			repo_objects.field_data
			    .arr[repo_objects.field_data.nCount]
			    .object_type = asn1SccALPHA_OBJECT_TYPE_directory;
		} else if (info.type == LFS_TYPE_REG) {
			repo_objects.field_data
			    .arr[repo_objects.field_data.nCount]
			    .object_type = asn1SccALPHA_OBJECT_TYPE_file;
		}
		strncpy(
		    repo_objects.field_data.arr[repo_objects.field_data.nCount]
			.object_name.field_data,
		    info.name,
		    asn1SccALPHA_OBJECT_NAME_REQUIRED_BYTES_FOR_ENCODING + 1);
		repo_objects.field_data.arr[repo_objects.field_data.nCount]
		    .object_name.field_data
			[asn1SccALPHA_OBJECT_NAME_REQUIRED_BYTES_FOR_ENCODING] =
		    '\0';
		repo_objects.field_data.nCount++;
	}

	lfs_dir_close(&lfs, &dir);
	filesystem_RI_report_content_of_repository_request_respond(
	    IN_repository_path, &repo_objects);
}

void filesystem_PI_write_object_memory(
    const asn1SccGAMMA_MEMORY_BASE *IN_memory_base,
    const asn1SccGAMMA_MEMORY_OFFSET *IN_offset,
    const asn1SccGAMMA_MEMORY_DATA *IN_content,
    asn1SccGAMMA_BOOLEAN *OUT_result)

{
	if (IN_memory_base->kind != GAMMA_MEMORY_BASE_fs_memory_PRESENT) {
		*OUT_result = false;
		return;
	}

	lfs_file_t file;
	int offset = *IN_offset;
	int length = IN_content->field_data.nCount;

	uint8_t buffer[cfg.cache_size];
	memset(buffer, 0, cfg.cache_size);

	struct lfs_attr file_attrs[8];

	struct lfs_file_config file_config = {
	    .buffer = buffer, .attrs = file_attrs, .attr_count = 0};

	int return_code = lfs_file_opencfg(
	    &lfs, &file, IN_memory_base->u.fs_memory.field_data,
	    LFS_O_RDWR | LFS_O_CREAT, &file_config);
	if (return_code < 0) {
		*OUT_result = false;
		return;
	}

	if (offset != lfs_file_seek(&lfs, &file, offset, LFS_SEEK_SET)) {
		*OUT_result = false;
		return;
	}

	if (length !=
	    lfs_file_write(&lfs, &file, IN_content->field_data.arr, length)) {
		*OUT_result = false;
		return;
	}

	return_code = lfs_file_close(&lfs, &file);
	if (return_code < 0) {
		*OUT_result = false;
		return;
	}

	*OUT_result = true;
}

int block_device_read(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, void *buffer, lfs_size_t size)
{
	const asn1SccMEMORY_BLOCK_INDEX block_index = block;
	const asn1SccMEMORY_OFFSET block_offset = off;
	asn1SccMEMORY_DATA data;
	const asn1SccMEMORY_SIZE data_size = size;
	asn1SccT_Int32 return_code;

	memset(data.arr, 0, asn1SccMEMORY_DATA_REQUIRED_BYTES_FOR_ENCODING - 1);
	data.nCount = size;

	filesystem_RI_memory_read(&block_index, &block_offset, &data,
				  &data_size, &return_code);

	memcpy(buffer, data.arr, size);

	return return_code;
}

int block_device_prog(const struct lfs_config *c, lfs_block_t block,
		      lfs_off_t off, const void *buffer, lfs_size_t size)
{
	const asn1SccMEMORY_BLOCK_INDEX block_index = block;
	const asn1SccMEMORY_OFFSET block_offset = off;
	asn1SccMEMORY_DATA data;
	const asn1SccMEMORY_SIZE data_size = size;
	asn1SccT_Int32 return_code;

	memcpy(data.arr, buffer, size);
	data.nCount = size;

	filesystem_RI_memory_program(&block_index, &block_offset, &data,
				     &data_size, &return_code);

	return return_code;
}

int block_device_erase(const struct lfs_config *c, lfs_block_t block)
{
	const asn1SccMEMORY_BLOCK_INDEX block_index = block;
	asn1SccT_Int32 return_code;

	filesystem_RI_memory_erase(&block_index, &return_code);

	return return_code;
}

int block_device_sync(const struct lfs_config *c)
{
	asn1SccT_Int32 return_code;

	filesystem_RI_memory_sync(&return_code);

	return return_code;
}
